#!/bin/bash

NEW_OPTS=''
FILLED=''

while getopts "csSn:fCrRe hbdWALP" opt; do
  case $opt in
    c)
      clear # console
      FILLED=1
    ;;

    s)
      python3 -m http.server -d ./_landing/ 8000 # server landing
      exit 0
    ;;

    S)
      python3 -m http.server -d ./_web/ 8001 # server web
      exit 0
    ;;

    n)
      dart scripts/rename.dart "$OPTARG"
      exit 0
    ;;

    f)
      dart format .
      FILLED=1
    ;;

    C)
      flutter clean
      FILLED=1
    ;;

    r)
      flutter clean && flutter run -d chrome
      exit 0
      ;;

    R)
      flutter clean && flutter run -d linux
      exit 0
    ;;
    e)
      echo -e "$(cat scripts/examples.txt)"
      exit 0
    ;;
    h | b | d | W | A | L | P)
      NEW_OPTS="$NEW_OPTS$opt"
    ;;
    *)
      echo "Loosing option"
      exit 0
    ;;
  esac
done
shift $((OPTIND-1))


if [ "$NEW_OPTS" != "" ]; then
  dart scripts/wrk.dart "-$NEW_OPTS"
elif [ "$FILLED" != "1" ]; then
  echo -e "Empty options. See help -h.\n"
  dart scripts/wrk.dart -h
fi
